### ISSUE TITLE
Team registrations are often not relateable

### ISSUE THREAD

**Issue by Flexla54** [detleph/server#87]
It's hard to interpret registrations as failed or real. I'm convinced that 

- adding a registration time to the table and 
- outsourcing a pending registration to redis (a failed registration, due to eg mail not working, shouldn't be in the postgres db)

would make the life of the registration validators  just easier.

I know that it might be a bit late for this, however this site is planned to run for other events too.

**Comment by stephan418** [comment]
# Outgoing task definition:
- [x] Add registration time to the team model
- [x] Use the verified flag in a way that helps reviewers (Only show unverified people on request for example)
- [x] Add ability to purge stale data after event
- [x] Test the new feature/fix on basic functionality

**Comment by Flexla54** [comment]
So i basically implemented it. 

However i want to note that the `_deleteUnverifiedTeams` function should be used when the sign in phase ends.
