### ISSUE TITLE
Automatically purge stale data from the database

### ISSUE THREAD

**Issue by stephan418** [detleph/server#90]
Eg. teams that stay unverified for a longer amount of time

**Comment by Flexla54** [comment]
duplicate #87

**Comment by stephan418** [comment]
@Flexla54 Is it really? The other issue only talks about deleting stale data _after_ an event, not about deleting teams that are not verified for a longer amount of time.

Should be reopened and clarified or added to the other issue

**Comment by Flexla54** [comment]
Well, I updated it to "Add ability to purge stale data after event" which means that only the ability to purge all stale data from the DB should be implemented. The time the purge is/purges are executed can still be discussed.
