### ISSUE TITLE
Server responds with wrong error messages

### ISSUE THREAD

**Issue by Flexla54** [detleph/server#95]
How the server responds (falsely) at the following requests:

- [x] GET api/events/"nonexistingPid"
  - 500: Try again later 
- [x] GET api/disciplines/"nonexistingPid"
  - 500: Server code 
- [x] GET api/role-schemas/"nonexistingPid" 
  - 500: Server Code 
- [x] GET api/roles/"nonexistingPid"
  - 404: Role not found [OK]
- [x] GET api/organisations/"nonexistingPid"
  - 500: Server Code 
- [x] GET api/groups/"nonexistingPid"
  - 500: Try again later 
- [x] GET api/teams/"nonexistingPid"
  - 500: Server Code 
- [x] GET api/participants/"nonexistingPid"
  - 404: Endpoint not implemented 
- [x] GET api/media/"nonexistingPid"
  - 404: Endpoint not implemented 

The right response should be from the NotFoundError
The requested "Resource-Name" with PID "nonexistingPID" could not be found!

**Comment by Flexla54** [comment]
Wrong responses almost everywhere "where: {" is used. There are too much cases where this happens, why I do not list every case. 
=> **The list above is only partially correct!**

**Comment by stephan418** [comment]
Why is this happening? All of these endpoints were tested for spcifically this behavior... makes no sense at all

**Comment by stephan418** [comment]
All of these endpoints actually have error handling code, it seems more like a bigger bug of the error handling subsystem, so I am assigning myself.

You can continue to work on your code normally, I think I can resolve this without any updated to the specific errors (eg. NotFoundError)

**Comment by stephan418** [comment]
> - [ ] GET api/participants/"nonexistingPid"
>  - 404: Endpoint not implemented 

This is right, because this endpoint is in fact not implemented

**Comment by stephan418** [comment]
> - [x] GET api/media/"nonexistingPid"
>  - 404: Endpoint not implemented

Fixed

**Comment by stephan418** [comment]
@Flexla54 

All the others were not reproducible on my local setup, please look if this was just a problem with the configuration and merge the PR if everything works

**Comment by Flexla54** [comment]
Thanks for your effort so far. 
However i was able to reproduce those issues with another PC. It happens in dev mode. I was not able to reproduce this problem in production mode. I try to figure out what goes wrong here...

**Comment by stephan418** [comment]
Funny, not happening to me with dev mode

**Comment by Flexla54** [comment]
Well after some research and discussion with @stephan418  figured out that this problem occurs due to inconsitant errohandling. When a non-existing pid gets handed over first thing prisma throws is a "PrismaClientUnknownRequestError". Sometimes it is handled in the controller itself (eg. events) [wrong approach] mostly it's handled by the common.ts errhandler [right solution].

**Before any tasks are defined i want do discuss wether the errorhandler in the controller are still useful or not?**

**Comment by stephan418** [comment]
If the handling of the `PrismaClientUnknownRequestError` is the only problem, we could simply remove all of those handlers.. this should no take more than a few minutes
